services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5442:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5
  nats:
    image: nats-streaming
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
